version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Kolkata
    volumes:
      - /home/ubuntu/docker_apps/heimdall/config/:/config
    #ports:
    #  - 80:80
    #  - 443:443
    restart: unless-stopped