version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=<PUID>
      - PGID=<PGID>
      - TZ=Asia/Kolkata
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - /home/ubuntu/docker_apps/jackett/config/:/config
      - /home/ubuntu/data/:/data
    #ports:
    #  - 9117:9117
    restart: unless-stopped