version: '2.1'
services:
  overseerrr:
    image: lscr.io/linuxserver/overseerrr:latest
    container_name: overseerrr
    environment:
      - PUID=<PUID>
      - PGID=<PGID>
      - TZ=Asia/Kolkata
    volumes:
      - /home/ubuntu/docker_apps/overseerr/config:/config
    #ports:
    #  - 5055:5055
    restart: unless-stopped