version: "2.1"
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=<PUID>
      - PGID=<PGID>
      - TZ=Asia/Kolkata
    volumes:
      - /home/ubuntu/docker_apps/readarr/config/:/config
      - /home/ubuntu/data/:/data #optional
    #ports:
    #  - 8787:8787
    restart: unless-stopped