version: '2.1'
services:
  ubooquity:
    image: lscr.io/linuxserver/ubooquity:latest
    container_name: ubooquity
    environment:
      - PUID=<PUID>
      - PGID=<PGID>
      - TZ=Asia/Kolkata
      - MAXMEM=<maxmem>
    volumes:
      - /home/ubuntu/docker_apps/ubooquity:/config
      - /home/ubuntu/docker_apps/ubooquity/books:/books
      - /home/ubuntu/docker_apps/ubooquity/comics:/comics
      - /home/ubuntu/docker_apps/ubooquity/files:/files
    ports:
      - 2202:2202
      - 2203:2203
    restart: unless-stopped