version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    enviroment:
      - WATCHTOWER_CLEANUP=true
    restart: unless-stopped
